/** Renders the typed route map (`src/router/route-map.gen.d.ts`) from parsed route records. */
import type { RouteInfo } from '../types';

interface ParamType {
  raw: string;
  normalized: string;
  optional: boolean;
}

/** Parses `:id`, `:id?`, `:pathMatch(.*)*` etc. out of a route path into vue-router's param shape. */
function parseParams(path: string): Record<string, ParamType> {
  const params: Record<string, ParamType> = {};
  const re = /:(\w+)(\([^)]*\))?([?*+]?)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(path))) {
    const [, name, , modifier] = m;
    const repeated = modifier === '*' || modifier === '+';
    const optional = modifier === '*' || modifier === '?';
    const raw = repeated ? '(string | number)[]' : 'string | number';
    const normalized = repeated ? 'string[]' : 'string';
    params[name] = { raw, optional, normalized };
  }
  return params;
}

function paramsType(params: Record<string, ParamType>, kind: 'raw' | 'normalized'): string {
  const keys = Object.keys(params);
  if (keys.length === 0) return 'Record<never, never>';
  return `{ ${keys.map((k) => `${k}${params[k].optional ? '?' : ''}: ${params[k][kind]}`).join('; ')} }`;
}

export function renderRouteMap(routes: RouteInfo[]): string {
  const named = routes.filter((r): r is RouteInfo & { name: string } => !!r.name);
  const byName = new Map<string, RouteInfo>();
  for (const r of named) {
    if (byName.has(r.name)) {
      throw new Error(`renderRouteMap: duplicate route name "${r.name}" (${byName.get(r.name)!.file} and ${r.file})`);
    }
    byName.set(r.name, r);
  }

  const sorted = [...byName.keys()].sort();
  const entries = sorted.map((name) => {
    const route = byName.get(name)!;
    const params = parseParams(route.path);
    const rawType = paramsType(params, 'raw');
    const normalizedType = paramsType(params, 'normalized');
    return `  '${name}': RouteRecordInfo<'${name}', '${route.path}', ${rawType}, ${normalizedType}>;`;
  });

  return `// GENERATED by \`bun run memory\` from src/modules/*/routes — do not edit.
import type { RouteRecordInfo } from 'vue-router';

export interface RouteNamedMap {
${entries.join('\n')}
}

declare module 'vue-router' {
  interface TypesConfig { RouteNamedMap: RouteNamedMap }
}
`;
}
