/**
 * Render stage: Inventory → { repo-relative path: content }. One index, one file per module (so an
 * agent working on one domain loads only that file), one mock-engine file, and the full JSON.
 */
import { config } from './config';
import type { Disposition, Inventory, ServiceFn, TypeDecl } from './types';

const HEADER = (what: string) =>
  `<!-- Generated by \`bun run contract\` (scripts/contract). Do not edit — change the code or scripts/contract/config.ts. -->\n\n# ${what}\n\n`;
const DISPOSITIONS: Disposition[] = ['port', 'rust-existing', 'frontend', 'dev-only', 'drop'];
const cell = (s: string, max = 110) => {
  const flat = s.replace(/\s+/g, ' ').replace(/\|/g, '\\|');
  return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat;
};
const code = (s: string, max?: number) => (s ? `\`${cell(s, max)}\`` : '');
const list = (xs: string[]) => xs.join(', ');
const short = (id: string) => id.replace(/^src\/mocks\//, '').replace(/\.ts#/, '#');

function renderIndex(inv: Inventory, modules: string[]): string {
  const byDisp = (fns: ServiceFn[], d: Disposition) => fns.filter((f) => f.disposition === d).length;
  let md = HEADER('Backend contract inventory');
  md += 'Every service function the pages call (the seam), what it touches in the mock backend, and what the\n';
  md += 'Rust backend should do with it. Source of truth for plans/pending/21-rust-backend Part 01. Dispositions\n';
  md += 'are **heuristic suggestions** until a reviewer confirms them in `scripts/contract/config.ts` → `overrides`.\n\n';
  md += `**${inv.services.length}** wrapped service functions · **${inv.tables.length}** MockDb tables · **${inv.types.length}** exported module types · **${inv.mockFns.length}** mock-engine functions · **${inv.pathLinks.length}** path-string links to convert.\n\n`;

  md += '## Modules\n\n| Module | Fns | ' + DISPOSITIONS.join(' | ') + ' | Writes tables | Shared managers | File |\n|' + '---|'.repeat(DISPOSITIONS.length + 5) + '\n';
  for (const m of modules) {
    const fns = inv.services.filter((f) => f.module === m);
    const writes = [...new Set(fns.flatMap((f) => (f.disposition === 'port' ? f.closure.writes : [])))].sort();
    const caps = [...new Set(fns.flatMap((f) => f.closure.capabilities))].sort();
    md += `| **${m}** | ${fns.length} | ${DISPOSITIONS.map((d) => byDisp(fns, d) || '').join(' | ')} | ${writes.length} | ${list(caps)} | [${m}.md](${m}.md) |\n`;
  }

  md += '\n## Shared managers (master plan §3 rule 3)\n\nWhich service functions reach each capability — every one of them must go through that `shared::` module in Rust.\n\n| Capability | Mock entry points | Service fns | Modules |\n|---|---|---|---|\n';
  for (const [cap, ids] of Object.entries(config.capabilities)) {
    const fns = inv.services.filter((f) => f.closure.capabilities.includes(cap));
    md += `| **${cap}** | ${ids.map((i) => code(short(i))).join(', ')} | ${fns.length} | ${list([...new Set(fns.map((f) => f.module))].sort())} |\n`;
  }

  md += '\n## Tables (entity ownership hints for Part 02)\n\n"Written by" is a lower bound (see `scripts/contract/types.ts` → `FnFacts.writes`).\n\n| Table | Read by (fns) | Written by (fns) | Writer modules |\n|---|---|---|---|\n';
  for (const t of inv.tables) {
    const readers = inv.services.filter((f) => f.closure.tables.includes(t));
    const writers = inv.services.filter((f) => f.closure.writes.includes(t));
    md += `| \`${t}\` | ${readers.length} | ${writers.length} | ${list([...new Set(writers.map((f) => f.module))].sort())} |\n`;
  }

  md += '\n## Path-string links (must become named route objects — CLAUDE.md rule 25)\n\n';
  md += inv.pathLinks.length ? '| File | Line | Literal |\n|---|---|---|\n' + inv.pathLinks.map((l) => `| \`${l.file}\` | ${l.line} | ${code(l.text, 80)} |`).join('\n') + '\n' : '_none_\n';

  md += '\n## Unwrapped service exports (not endpoints — helpers, constants, re-exports)\n\n';
  md += inv.unwrapped.map((u) => `\`${u.module}.${u.name}\``).join(' · ') + '\n';
  return md;
}

function renderTypes(types: TypeDecl[]): string {
  if (!types.length) return '_no exported types in this module_\n';
  return types
    .map((t) => {
      const head = `### \`${t.name}\` (${t.kind}, \`${t.file}:${t.line}\`)\n\n`;
      if (!t.fields) return `${head}\`${cell(t.text ?? '', 400)}\`\n`;
      return head + t.fields.map((f) => `- \`${f.name}${f.optional ? '?' : ''}: ${cell(f.type, 160)}\`${f.hint ? ` — _${f.hint}_` : ''}`).join('\n') + '\n';
    })
    .join('\n');
}

function renderModule(inv: Inventory, m: string): string {
  const fns = inv.services.filter((f) => f.module === m);
  let md = HEADER(`Contract — \`${m}\``);
  md += `${fns.length} service functions. Full signatures: \`${config.jsonFile}\`. Plan: plans/pending/21-rust-backend/01-frontend-analysis/${m}.md.\n\n`;
  md += '| Function | Params | Returns | Disposition | Writes | Reads (other) | Shared | DTO types |\n|---|---|---|---|---|---|---|---|\n';
  for (const f of fns) {
    const reads = f.closure.tables.filter((t) => !f.closure.writes.includes(t));
    const params = f.params.map((p) => `${p.name}${p.optional ? '?' : ''}: ${p.type}`).join(', ');
    md += `| [\`${f.name}\`](../../../${f.file}#L${f.line}) | ${code(params, 90)} | ${code(f.returns, 90)} | **${f.disposition}** — ${cell(f.dispositionReason, 60)} | ${list(f.closure.writes)} | ${cell(list(reads), 120)} | ${list(f.closure.capabilities)} | ${list(f.dtoTypes)} |\n`;
  }
  md += `\n## Types (\`src/modules/${m}/types\`)\n\nHints: _decimal_ → \`rust_decimal::Decimal\` / \`DECIMAL\`, _uuid_ → UUIDv7, _date_ → local date/datetime, _route_ → \`RouteRef { name, params }\`, _enum_ → Rust enum.\n\n`;
  md += renderTypes(inv.types.filter((t) => t.module === m));
  return md;
}

function renderMocks(inv: Inventory): string {
  let md = HEADER('Mock engine functions (`src/mocks/backend` + `db.ts`)');
  md += 'The executable spec the Rust `shared/` and `domains/` port. Rounding counts show where `round2`/`round4` is applied — the Rust port must round at exactly these points (decision D3).\n\n';
  md += '| Function | Reads | Writes | Calls (mock) | round2 | round4 | Capability |\n|---|---|---|---|---|---|---|\n';
  for (const f of inv.mockFns) {
    const caps = Object.entries(config.capabilities).filter(([, ids]) => ids.includes(f.id)).map(([c]) => c);
    const mockCalls = f.calls.filter((c) => c.startsWith(config.mocksDir + '/')).map(short);
    md += `| [\`${short(f.id)}\`](../../../${f.file}#L${f.line}) | ${cell(list(f.tables.filter((t) => !f.writes.includes(t))), 90)} | ${list(f.writes)} | ${cell(list(mockCalls), 140)} | ${f.round2 || ''} | ${f.round4 || ''} | ${list(caps)} |\n`;
  }
  return md;
}

export function render(inv: Inventory): Record<string, string> {
  const modules = [...new Set([...inv.services.map((f) => f.module), ...inv.types.map((t) => t.module)])].sort();
  const out: Record<string, string> = {
    [`${config.outDir}/README.md`]: renderIndex(inv, modules),
    [`${config.outDir}/mocks.md`]: renderMocks(inv),
    [`${config.outDir}/${config.jsonFile}`]: JSON.stringify(inv, null, 2) + '\n',
  };
  for (const m of modules) out[`${config.outDir}/${m}.md`] = renderModule(inv, m);
  return out;
}
